### PR TITLE
feat(store): migrate all callers from rusqlite to sqlx pool

### LINKED ISSUE #34: feat(store): migrate callers from rusqlite _conn() to sqlx _pool() functions
## Background

PR #33 added async sqlx pool functions (`*_pool`) alongside existing sync rusqlite functions (`*_conn`) across 22 files (60+ pool functions). No callers have been migrated yet.

## Scope

Migrate callers to use the new async pool functions:

| Caller | `_conn()` calls | Notes |
|--------|:---:|-------|
| `src/serve.rs` | 14 | tiny_http sync server — needs spawn_blocking or axum migration |
| `src/mem/axum_server.rs` | ~20 | Arc<Mutex<Connection>> → SqlitePool, full handler rewrite |
| `src/hooks/observe.rs` | 2 | CLI hook, sync |
| `src/hooks/reflect.rs` | 12 | CLI hook, sync — largest caller |
| `src/hooks/snapshot.rs` | 3 | CLI hook, sync |
| `src/hooks/resume.rs` | 3 | CLI hook, sync |
| `src/evolve/ingest.rs` | 47 | CLI operation, largest single-file caller |
| `src/evolve/instincts.rs` | 1 | CLI operation |
| `src/evolve/skills.rs` | 1 | CLI operation |

## Approach

Hooks and evolve commands run as short-lived CLI processes. Two migration strategies:

1. **spawn_blocking bridge**: Wrap `_pool()` calls in `tokio::task::spawn_blocking` to keep sync call sites
2. **Full async rewrite**: Convert callers to `async fn` with `#[tokio::main]` runtime

Strategy 1 is lower risk for CLI hooks (process-per-invocation). Strategy 2 is needed for `serve.rs` and `axum_server.rs`.

## Acceptance Criteria

- [ ] All callers use `_pool()` functions
- [ ] `#[allow(dead_code)]` removed from pool functions
- [ ] All existing tests pass
- [ ] `cargo clippy -- -D warnings` clean

### PR DESCRIPTION
**Pull request by epicsagas**
## Summary

Converts all remaining rusqlite `_conn()` callers in `mem/`, `evolve/`, and `hooks/` to use the async `block_on(*_pool())` bridge introduced in PR #33. Also rewrites `store/migrate.rs` to use `SqliteConnectOptions` direct connection + raw sqlx query for `ATTACH DATABASE`.

### Changes

- `src/mem/mcp.rs` — `open_db()` → `block_on(memory_pool())`; all `*_conn()` → pool variants
- `src/mem/graph.rs` — `build_graph_conn`, `rebuild_graph_json_conn`, etc. → pool variants
- `src/evolve/ingest.rs` — 47 `*_conn()` calls converted, `ImmediateTx` removed
- `src/evolve/instincts.rs` — `open_db()` → `block_on(memory_pool())`
- `src/hooks/reflect.rs` — 3 remaining `*_conn()` calls converted
- `src/mem/axum_server.rs` — `handle_stats`, `handle_list_nodes` use async pool
- `src/mem/store/*.rs` — `_conn()` function definitions removed
- `src/store/migrate.rs` — Full rewrite: `rusqlite::Connection` → `SqliteConnectOptions::new().filename(...).connect().await`; ATTACH DATABASE as raw sqlx query
- `src/store/mod.rs` — Remove `ImmediateTx`, `open_harness_db()`, `store_err()`
- `src/store/pool.rs` — `OnceCell` → `TokioMutex` for integration test URL-change detection

## Test plan

- [ ] `cargo test` — 549 tests pass
- [ ] `cargo clippy --all-targets -- -D warnings` — clean
- [ ] `cargo fmt --check` — clean
- [ ] `grep -r "use rusqlite" src/` — empty (no rusqlite imports outside migrate.rs comments)

Closes #34

---
*Part of [#35](#) → [#36](#) stacked series completing full rusqlite removal.*

### CODE REVIEW

**Comment by epicsagas** [comment]
Closing in favor of a single consolidated PR to avoid compilation errors in stacked branch isolation. All changes (R1+R2+R3+R4) will be in one PR closing #34, #35, #36.
